import type { LearningScenario } from "../lib/simulator";

export const demandCapacityScenario: LearningScenario = {
  id: "demand-capacity",
  title: "Handle a short-term demand and capacity gap",
  shortTitle: "Demand & Capacity",
  useCase: "Demand & Capacity Management",
  asset: "PART-AX19",
  goal: "A customer needs more units next week and a supplier must share realistic capacity information without exposing its entire planning system.",
  supplierLabel: "Production Supplier",
  manufacturerLabel: "Customer / OEM",
  steps: [
    {
      id: "demand-signal",
      technicalName: "Demand Signal",
      question: "What changed on the customer side?",
      business: "The customer now needs more PART-AX19 units in a specific time window. The supplier needs a clear demand signal before it can react.",
      architecture: "Demand information is represented as structured business data that can be exchanged between independent planning systems.",
      developer: "The scenario starts with a machine-readable demand payload identified by part, quantity and time horizon rather than an email or spreadsheet attachment.",
      whyNeeded: "Capacity planning only works when both sides discuss the same part, quantity and time period.",
      withoutIt: "Teams coordinate shortages through calls and spreadsheets that quickly become outdated.",
      actionLabel: "Send the demand signal",
      direction: "manufacturer-to-supplier",
      mapFocus: ["manufacturer", "consumer-edc", "dataspace", "supplier-edc", "supplier"],
      glossary: ["Dataspace", "Consumer", "Provider"],
      payload: "PART-AX19 → +1,500 units → next week",
    },
    {
      id: "capacity-picture",
      technicalName: "Capacity Information",
      question: "What can the supplier realistically produce?",
      business: "The supplier answers with the capacity it can commit for the same part and period, without opening its full production-planning database.",
      architecture: "The provider exposes only the agreed planning information as a controlled data offer.",
      developer: "Capacity data is prepared as a bounded business payload and offered through the provider-side dataspace interface.",
      whyNeeded: "The customer needs a decision-ready capacity picture, not unrestricted access to the supplier's internal planning system.",
      withoutIt: "Either the customer gets too little information or the supplier exposes far more operational data than necessary.",
      actionLabel: "Prepare capacity data",
      direction: "supplier-to-manufacturer",
      mapFocus: ["supplier", "supplier-edc", "policy"],
      glossary: ["Provider", "Policy", "Data Sovereignty"],
    },
    {
      id: "shared-planning-model",
      technicalName: "Shared Semantics",
      question: "How do both systems interpret quantity and time in the same way?",
      business: "A demand of 1,500 is meaningless if one system means pieces per day and the other means pieces per week. The planning data needs shared meaning.",
      architecture: "Standardized semantic models align the structure and meaning of demand, delivery and capacity information.",
      developer: "The producer and consumer validate the planning payload against the agreed semantic model/version before comparing values.",
      whyNeeded: "Planning decisions require comparable values, units and periods across company systems.",
      withoutIt: "The exchange succeeds technically while the business comparison is still wrong.",
      actionLabel: "Align the planning meaning",
      direction: "both",
      mapFocus: ["semantic-model", "supplier", "manufacturer"],
      glossary: ["Semantic Model", "Interoperability"],
    },
    {
      id: "controlled-planning-exchange",
      technicalName: "Controlled Exchange",
      question: "Should every customer see this supplier capacity?",
      business: "No. Capacity can be commercially sensitive, so the supplier decides which participant may receive which planning information.",
      architecture: "Identity, catalog visibility, policy and agreement govern the exchange before capacity data is delivered.",
      developer: "The consumer discovers the relevant offer and satisfies its policy before the connector transfer process exposes the capacity payload.",
      whyNeeded: "Sensitive planning information needs the same data-sovereignty controls as other cross-company data.",
      withoutIt: "A useful planning API can accidentally become an uncontrolled source of commercially sensitive information.",
      actionLabel: "Authorize the exchange",
      direction: "both",
      mapFocus: ["identity", "supplier-edc", "policy", "dataspace", "consumer-edc"],
      glossary: ["Identity", "Catalog", "Policy", "Agreement"],
    },
    {
      id: "shortfall",
      technicalName: "Demand-Capacity Comparison",
      question: "What decision can the companies make now?",
      business: "They can compare the requested quantity with available capacity, see the shortfall and coordinate an updated plan before the shortage becomes a production stop.",
      architecture: "The application combines standardized demand and capacity data after controlled exchange to calculate a common planning view.",
      developer: "The consumer application aligns part identifiers and time buckets, computes the gap and can repeat the exchange when demand or capacity changes.",
      whyNeeded: "The goal is not merely to transfer planning data; it is to detect and resolve supply risk earlier.",
      withoutIt: "The same shortage becomes visible much later through missed deliveries or production disruption.",
      actionLabel: "Calculate the gap",
      direction: "both",
      mapFocus: ["supplier", "dataspace", "manufacturer", "semantic-model"],
      glossary: ["Demand & Capacity", "Interoperability"],
      payload: "Demand 5,000 − capacity 4,200 = shortfall 800 units",
    },
  ],
  challenges: [
    {
      id: "wrong-time-bucket",
      title: "The numbers look impossible",
      prompt: "The supplier reports 4,200 units of capacity and the customer reports 5,000 units of demand, but the applications disagree on the size of the shortage. What should you verify first?",
      symptom: "Exchange ✅  Values received ✅  Comparison ❌",
      hint: "Look at how each side defines the period and unit behind the number.",
      correctOptionId: "semantics",
      rootCause: "The two systems are comparing different units or time buckets because their semantic expectations are not aligned.",
      options: [
        { id: "semantics", label: "Compare units, time buckets and semantic model versions", explanation: "Correct. A successful transfer can still produce a wrong planning result when the values mean different things." },
        { id: "dns", label: "Change the connector DNS name", explanation: "Connectivity already succeeded, so DNS does not explain a business-value mismatch." },
        { id: "identity", label: "Create another participant identity", explanation: "Identity already allowed the exchange and does not fix incompatible planning semantics." },
      ],
    },
    {
      id: "capacity-offer-hidden",
      title: "The customer cannot see the capacity offer",
      prompt: "The supplier says the capacity dataset exists, but this customer cannot discover the offer. What should be checked?",
      symptom: "Supplier dataset ✅  Customer catalog offer ❌",
      hint: "Catalogs can be participant-dependent. Think about identity and the rules controlling offer visibility.",
      correctOptionId: "visibility",
      rootCause: "The customer is not eligible for the offer because its participant identity or policy-related attributes do not match the provider's access rules.",
      options: [
        { id: "visibility", label: "Check participant identity and offer access policy", explanation: "Correct. A provider can expose different offers depending on who is asking." },
        { id: "spreadsheet", label: "Email the full production plan instead", explanation: "That bypasses the controlled exchange rather than diagnosing it." },
        { id: "pcf", label: "Update the PCF model", explanation: "Carbon-footprint semantics are unrelated to demand-capacity offer visibility." },
      ],
    },
  ],
};
