import type { LearningScenario } from "../lib/simulator";

export const qualityScenario: LearningScenario = {
  id: "quality-management",
  title: "Share a supplier quality finding with the manufacturer",
  shortTitle: "Quality",
  useCase: "Quality Management",
  asset: "PART-QA-204",
  goal: "A supplier detects a quality issue on a delivered part and needs to share a precise, interpretable finding without exposing its internal quality system.",
  supplierLabel: "Quality Supplier",
  manufacturerLabel: "Vehicle Manufacturer",
  steps: [
    {
      id: "quality-finding",
      technicalName: "Quality Finding",
      question: "What exactly was found on the supplied part?",
      business: "The supplier starts with a concrete quality finding tied to a real part or batch, not a vague message that something may be wrong.",
      architecture: "The quality application produces a structured finding anchored to a known asset identifier so downstream systems can connect it to the right digital representation.",
      developer: "The source application emits a machine-readable result containing the asset identifier, finding type, timestamp and evidence references instead of a free-text email.",
      whyNeeded: "A quality decision is only useful when everybody knows which asset and observation it refers to.",
      withoutIt: "Teams spend time matching screenshots, ticket numbers and ERP records before they can even discuss the same defect.",
      actionLabel: "Anchor the finding to the part",
      direction: "internal",
      mapFocus: ["supplier", "digital-twin"],
      glossary: ["Asset", "Digital Twin", "Quality Result"],
      payload: "PART-QA-204 → surface anomaly → inspection result",
    },
    {
      id: "shared-quality-meaning",
      technicalName: "Standardized Quality Semantics",
      question: "How does the manufacturer know what the finding means?",
      business: "A defect label only helps when both companies interpret the fields, status and evidence in the same way.",
      architecture: "A shared semantic model gives the quality payload a common structure and meaning across supplier and manufacturer applications.",
      developer: "The exchanged result follows an agreed semantic identifier and model version so applications can validate fields and units consistently.",
      whyNeeded: "Connectivity can move data, but semantics make that data interoperable.",
      withoutIt: "The payload arrives successfully but still needs custom translation for every partner.",
      actionLabel: "Align the quality model",
      direction: "both",
      mapFocus: ["semantic-model", "supplier", "manufacturer"],
      glossary: ["Semantic Model", "Interoperability", "Quality Result"],
    },
    {
      id: "discover-quality-offer",
      technicalName: "Catalog Offer",
      question: "How does the manufacturer request the quality data without knowing the supplier's internal API?",
      business: "The supplier exposes a discoverable offer for the permitted quality information instead of handing out direct access to its quality database.",
      architecture: "The provider connector publishes an offer that the consumer connector can discover through the dataspace catalog flow.",
      developer: "The consumer requests the provider catalog, selects the offer associated with the asset or quality dataset, and prepares for negotiation.",
      whyNeeded: "Partners need a repeatable discovery mechanism that is independent of internal application URLs.",
      withoutIt: "Every quality exchange becomes another manually maintained point-to-point integration.",
      actionLabel: "Discover the quality offer",
      direction: "manufacturer-to-supplier",
      mapFocus: ["supplier-edc", "dataspace", "consumer-edc"],
      glossary: ["Catalog", "Provider", "Consumer", "EDC"],
    },
    {
      id: "quality-policy",
      technicalName: "Usage Policy",
      question: "May the manufacturer use this finding for any purpose?",
      business: "The supplier can define which participant may access the result and under which business conditions it may be used.",
      architecture: "The provider attaches policy constraints to the quality-data offer and the connectors evaluate them before an agreement is created.",
      developer: "The negotiation succeeds only when consumer identity and attributes satisfy the machine-readable constraints of the selected offer.",
      whyNeeded: "Quality data can be commercially sensitive even when the receiving company is a legitimate partner.",
      withoutIt: "Authentication answers who the partner is, but not what that partner may do with a specific dataset.",
      actionLabel: "Evaluate the usage rules",
      direction: "supplier-to-manufacturer",
      mapFocus: ["identity", "policy", "supplier-edc", "consumer-edc"],
      glossary: ["Identity", "Policy", "Data Sovereignty"],
    },
    {
      id: "quality-transfer",
      technicalName: "Controlled Data Transfer",
      question: "How does the quality result reach the manufacturer now?",
      business: "After the agreement is accepted, the manufacturer receives the quality result while the supplier keeps its source system under its own control.",
      architecture: "The connector flow separates agreement from delivery and exposes only the data path covered by the negotiated offer.",
      developer: "A transfer process delivers or exposes the quality payload according to the configured data-plane pattern after agreement creation.",
      whyNeeded: "Permission and byte transfer are separate concerns and should fail independently.",
      withoutIt: "A valid agreement exists, but there is no governed mechanism for delivering the actual quality data.",
      actionLabel: "Transfer the quality result",
      direction: "supplier-to-manufacturer",
      mapFocus: ["supplier", "supplier-edc", "dataspace", "consumer-edc", "manufacturer"],
      glossary: ["Agreement", "Data Transfer", "Data Plane"],
      payload: "PART-QA-204 → standardized quality result → Manufacturer",
    },
  ],
  challenges: [
    {
      id: "quality-schema-mismatch",
      title: "The result arrives but the application rejects it",
      prompt: "Transport succeeded, but the manufacturer cannot parse the quality result. What should you compare first?",
      symptom: "Transfer ✅  Application validation ❌",
      hint: "The bytes arrived. Focus on whether both sides expected the same meaning and structure.",
      correctOptionId: "semantics",
      rootCause: "Supplier and manufacturer are using incompatible semantic model or schema versions for the quality result.",
      options: [
        { id: "semantics", label: "Compare semantic identifier and model version", explanation: "Correct. Successful transport does not guarantee semantic compatibility." },
        { id: "identity", label: "Create a new participant identity", explanation: "Identity already succeeded before the transfer and does not explain a schema error." },
        { id: "ui", label: "Reload the quality dashboard", explanation: "Reloading the UI cannot repair an incompatible payload structure." },
      ],
    },
    {
      id: "quality-policy-rejected",
      title: "The quality offer is visible but negotiation fails",
      prompt: "The manufacturer can discover the quality offer, yet no agreement is created. What is the best next check?",
      symptom: "Catalog ✅  Negotiation ❌",
      hint: "Discovery worked. Inspect the conditions attached to the selected offer.",
      correctOptionId: "policy",
      rootCause: "The consumer does not satisfy one of the policy constraints on the quality-data offer.",
      options: [
        { id: "policy", label: "Compare the offer policy with consumer attributes", explanation: "Correct. A visible offer can still be rejected during policy evaluation." },
        { id: "dtr", label: "Delete the Digital Twin Registry entry", explanation: "The current failure occurs in negotiation, not twin discovery." },
        { id: "database", label: "Share direct database credentials", explanation: "That bypasses the controlled dataspace exchange and is not the intended fix." },
      ],
    },
  ],
};
