import type { LearningScenario } from "../lib/simulator";

export const traceabilityScenario: LearningScenario = {
  id: "traceability",
  title: "Trace a quality issue through the supply chain",
  shortTitle: "Traceability",
  useCase: "Parts Traceability",
  asset: "BATCH-7A42",
  goal: "A manufacturer detects a quality issue and needs to understand which supplied parts are affected without asking every partner for spreadsheets.",
  supplierLabel: "Tier-1 Supplier",
  manufacturerLabel: "Vehicle Manufacturer",
  steps: [
    {
      id: "quality-event",
      technicalName: "Quality Event",
      question: "A defect is found. What is the first useful question?",
      business: "The manufacturer first needs to identify the affected batch or serialized part. Without a concrete asset, the investigation is only a vague supplier-wide alert.",
      architecture: "A quality event is anchored to an asset identifier that can be followed across digital representations and part relationships.",
      developer: "The application starts from a known batch or serialized-part identifier and uses standardized asset data as the root of the investigation.",
      whyNeeded: "A precise asset identifier turns a broad quality problem into a traceable investigation.",
      withoutIt: "Teams search manually across emails, ERP exports and supplier spreadsheets.",
      actionLabel: "Identify the affected batch",
      direction: "internal",
      mapFocus: ["manufacturer", "digital-twin"],
      glossary: ["Asset", "Digital Twin"],
      payload: "Quality event → BATCH-7A42",
    },
    {
      id: "relationships",
      technicalName: "Part Relationships",
      question: "Which components are connected to this affected part?",
      business: "The manufacturer needs to see what went into the part and where the part was used, so the possible impact can be narrowed quickly.",
      architecture: "Standardized bill-of-material and usage relationships connect parent and child assets across the supply chain.",
      developer: "Traceability applications resolve standardized as-built relationship aspects instead of relying on supplier-specific relation tables.",
      whyNeeded: "Quality impact is about relationships, not only isolated part records.",
      withoutIt: "A defect can be found, but teams cannot reliably tell which upstream or downstream assets are connected to it.",
      actionLabel: "Follow the part tree",
      direction: "internal",
      mapFocus: ["digital-twin", "semantic-model"],
      glossary: ["Digital Twin", "Submodel", "Semantic Model"],
    },
    {
      id: "partner-data",
      technicalName: "Sovereign Data Access",
      question: "What if some relationships belong to another company?",
      business: "The manufacturer should not need direct access to the supplier's internal ERP. It requests only the data that the supplier has agreed to share.",
      architecture: "Cross-company traceability uses controlled dataspace exchange between provider and consumer connectors.",
      developer: "The consumer discovers an offer, satisfies its policy and obtains the permitted traceability data through the connector flow.",
      whyNeeded: "A supply-chain graph spans companies that still need to keep control of their own systems.",
      withoutIt: "Traceability either stops at company boundaries or requires centralized copies of sensitive partner data.",
      actionLabel: "Request supplier relationships",
      direction: "manufacturer-to-supplier",
      mapFocus: ["supplier-edc", "dataspace", "consumer-edc", "policy"],
      glossary: ["EDC", "Policy", "Data Sovereignty"],
    },
    {
      id: "shared-meaning",
      technicalName: "Standardized Semantics",
      question: "How can different companies describe part relationships consistently?",
      business: "Supplier and manufacturer systems can use different internal names, but the exchanged relationship data needs one shared meaning.",
      architecture: "Semantic models define interoperable structures for part and relationship information across implementations.",
      developer: "The exchanged payload follows agreed aspect-model identifiers and versions so relationship fields can be processed consistently.",
      whyNeeded: "A graph is only useful when every participant means the same thing by parent, child, batch and serialized part.",
      withoutIt: "The data arrives, but each partner needs custom translation logic before the relationship can be trusted.",
      actionLabel: "Align the relationship model",
      direction: "both",
      mapFocus: ["semantic-model", "supplier", "manufacturer"],
      glossary: ["Semantic Model", "Interoperability"],
    },
    {
      id: "impact",
      technicalName: "Impact Analysis",
      question: "Now what can the manufacturer actually learn?",
      business: "The company can follow the affected batch through connected parts and identify which products, suppliers or customers may need action.",
      architecture: "Traceability applications combine discovered digital twins, standardized relationships and controlled partner data into a supply-chain view.",
      developer: "The application traverses the available relationship graph and keeps provenance for the assets and partner data used in the result.",
      whyNeeded: "The business value appears when technical exchange becomes a fast, explainable impact assessment.",
      withoutIt: "The organization still has data exchange, but incident response remains a manual coordination exercise.",
      actionLabel: "Show the affected chain",
      direction: "both",
      mapFocus: ["supplier", "supplier-edc", "dataspace", "consumer-edc", "manufacturer", "digital-twin"],
      glossary: ["Traceability", "Digital Twin"],
      payload: "BATCH-7A42 → supplier component → assembly → affected vehicles",
    },
  ],
  challenges: [
    {
      id: "missing-relation",
      title: "The trace stops at one supplier component",
      prompt: "The affected batch is found, but the application cannot continue to its child components. What should you verify first?",
      symptom: "Asset found ✅  Relationship traversal ❌",
      hint: "The part exists. The missing information is the connection between this part and the next assets.",
      correctOptionId: "relationship",
      rootCause: "The expected as-built relationship data is missing, incomplete or linked with the wrong asset identifier.",
      options: [
        { id: "relationship", label: "Check relationship data and asset identifiers", explanation: "Correct. Traversal depends on valid parent/child relationship information tied to the expected assets." },
        { id: "pcf", label: "Recalculate the product carbon footprint", explanation: "Carbon-footprint calculation does not repair missing part relationships." },
        { id: "frontend", label: "Change the page layout", explanation: "A UI change cannot create relationship data that is absent from the trace." },
      ],
    },
    {
      id: "supplier-boundary",
      title: "The graph stops at the company boundary",
      prompt: "Internal relationships are visible, but supplier-side traceability data cannot be loaded. What is the best next check?",
      symptom: "Internal graph ✅  Partner data ❌",
      hint: "The failure appears exactly when the investigation crosses into another participant's controlled data.",
      correctOptionId: "access",
      rootCause: "The partner offer is unavailable or the consumer does not satisfy the policy required to access it.",
      options: [
        { id: "access", label: "Check catalog offer, agreement and policy", explanation: "Correct. Cross-company data still requires a valid controlled exchange." },
        { id: "database", label: "Request direct supplier database credentials", explanation: "That defeats the dataspace model and is not the intended traceability flow." },
        { id: "identity-map", label: "Rename the batch in the UI", explanation: "Changing a display label does not create permission to load partner data." },
      ],
    },
  ],
};
